# turtle basics
from turtle import Turtle, Screen
my_turtle = Turtle()
my_turtle.shape("turtle")
my_turtle.color("violet")
my_turtle.forward(100)
my_turtle.color("blue")
my_turtle.right(90)
my_turtle.color("Green")
my_turtle.forward(100)
my_turtle.color("blue")
my_turtle.right(90)
my_turtle.color("yellow")
screen = Screen()
screen.exitonclick()